apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Name}}
data:
  # all-queries is used by DNS tests.
  all-queries: |
    kubernetes.cluster.local A
    kubernetes.svc.cluster.local A
    kubernetes.default.svc.cluster.local A
    google.com.svc.cluster.local A
    google.com.svc.cluster.local AAAA
    google.com.default.svc.cluster.local A
    google.com.default.svc.cluster.local AAAA
    google.com.cluster.local A
    google.com.cluster.local AAAA
    google.com A
    google.com AAAA
    small-service A
    small-service.{{ .Namespace }} A
    small-service.{{ .Namespace }}.svc.cluster.local A
    medium-service A
    medium-service.{{ .Namespace }} A
    medium-service.{{ .Namespace }}.svc.cluster.local A
    big-service A
    big-service.{{ .Namespace }} A
    big-service.{{ .Namespace }}.svc.cluster.local A
