apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: psp:default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: psp:unrestricted
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{.Namespace}}
